name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: | 
          echo "PORT=443" >> .env
          echo "HOSTNAME=localhost" >> .env
          echo "ADMIN_PW=$ADMIN_PW" >> .env
        env:
          ADMIN_PW: ${{ secrets.ADMIN_PW }}

      - name: (debug) Output file&dir
        run: ls -la

      - name: Deploy to production
        env:
          DEPLOY_URL: https://fileshare.yu-yu0202.f5.si
          SSL_KEY_PATH: /home/runner/src/SSL-CERTIFICATE/key.pem
          SSL_CERT_PATH: /home/runner/src/SSL-CERTIFICATE/cert.pem
        run: |
          mkdir -p /home/runner/work/FileShareService/FileShareService/src/SSL-CERTIFICATE/
          echo "${{ secrets.SSL_KEYPEM }}" > /home/runner/work/FileShareService/FileShareService/src/SSL-CERTIFICATE/key.pem
          echo "${{ secrets.SSL_CERTPEM }}" > /home/runner/work/FileShareService/FileShareService/src/SSL-CERTIFICATE/cert.pem
          echo "${{ secrets.SSL_FULLCHAINPEM }}" > /home/runner/work/FileShareService/FileShareService/src/SSL-CERTIFICATE/fullchain.pem
          npm run start
